#!/usr/bin/env python3
"""Track build performance by timing key build operations.

Runs each build step in isolation, measures its duration, and emits a
structured report. In CI, the report is written to $GITHUB_STEP_SUMMARY
so build timing is visible on every workflow run. Locally, the report
is printed to stdout and optionally saved as JSON.

Usage:
    python scripts/track_build_performance.py [--json report.json]
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
import time
from dataclasses import asdict, dataclass, field
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent


@dataclass
class StepResult:
    name: str
    duration_seconds: float
    success: bool
    command: str


@dataclass
class BuildReport:
    total_duration_seconds: float = 0.0
    steps: list[StepResult] = field(default_factory=list)
    cache_enabled: bool = False
    python_version: str = ""

    def add(self, result: StepResult) -> None:
        self.steps.append(result)
        self.total_duration_seconds += result.duration_seconds


def _run_step(name: str, command: list[str]) -> StepResult:
    """Run a command, time it, and return the result."""
    start = time.monotonic()
    try:
        subprocess.run(command, check=True, capture_output=True, cwd=REPO_ROOT)  # noqa: S603
        success = True
    except subprocess.CalledProcessError:
        success = False
    duration = time.monotonic() - start
    return StepResult(
        name=name,
        duration_seconds=round(duration, 2),
        success=success,
        command=" ".join(command),
    )


def run_build_steps(skip_tests: bool = False) -> BuildReport:
    """Run and time each build step, returning a structured report."""
    report = BuildReport()
    report.cache_enabled = os.getenv("UV_CACHE_DIR") is not None or os.getenv("GITHUB_ACTIONS") == "true"

    try:
        version_output = subprocess.run(  # noqa: S603
            [sys.executable, "--version"], capture_output=True, text=True, check=True
        )
        report.python_version = version_output.stdout.strip()
    except subprocess.CalledProcessError:
        report.python_version = "unknown"

    steps: list[tuple[str, list[str], bool]] = [
        ("Install dependencies (uv sync)", ["uv", "sync", "--extra", "dev"], False),
        ("Compile check", ["uv", "run", "python", "-m", "compileall", "-q", "src"], False),
        ("Lint (ruff check)", ["uv", "run", "ruff", "check", "src", "tests"], False),
        ("Format check (ruff format)", ["uv", "run", "ruff", "format", "--check", "src", "tests"], False),
        ("Type check (mypy)", ["uv", "run", "mypy", "src"], False),
    ]

    if not skip_tests:
        steps.append(("Tests (pytest)", ["uv", "run", "python", "-m", "pytest", "tests/", "--tb=short", "-q"], False))

    for name, command, _skip_on_fail in steps:
        result = _run_step(name, command)
        report.add(result)
        status = "PASS" if result.success else "FAIL"
        print(f"  [{status}] {name}: {result.duration_seconds}s")
        if not result.success and _skip_on_fail:
            print(f"  Skipping remaining steps due to {name} failure")
            break

    return report


def format_github_summary(report: BuildReport) -> str:
    """Format the report as a GitHub Actions step summary markdown table."""
    lines = [
        "## Build Performance Report",
        "",
        f"**Python**: {report.python_version}",
        f"**Cache enabled**: {'yes' if report.cache_enabled else 'no'}",
        f"**Total build time**: {report.total_duration_seconds}s",
        "",
        "| Step | Duration (s) | Status |",
        "|------|-------------|--------|",
    ]
    for step in report.steps:
        status = "pass" if step.success else "FAIL"
        lines.append(f"| {step.name} | {step.duration_seconds} | {status} |")
    lines.append("")
    lines.append("_Generated by `scripts/track_build_performance.py`_")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Track build performance metrics")
    parser.add_argument("--json", metavar="PATH", help="Save JSON report to file")
    parser.add_argument("--skip-tests", action="store_true", help="Skip pytest step")
    args = parser.parse_args()

    print("Running build steps and measuring performance...")
    report = run_build_steps(skip_tests=args.skip_tests)

    # Write JSON report if requested
    if args.json:
        output_path = Path(args.json)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        report_data = {
            "total_duration_seconds": report.total_duration_seconds,
            "cache_enabled": report.cache_enabled,
            "python_version": report.python_version,
            "steps": [asdict(s) for s in report.steps],
        }
        output_path.write_text(json.dumps(report_data, indent=2))
        print(f"\nJSON report saved to {output_path}")

    # Write to GitHub Actions step summary if in CI
    summary_path = os.getenv("GITHUB_STEP_SUMMARY")
    if summary_path:
        Path(summary_path).write_text(format_github_summary(report))
        print(f"\nGitHub Actions step summary written to {summary_path}")
    else:
        print(f"\n{format_github_summary(report)}")

    # Exit with error if any step failed
    all_passed = all(s.success for s in report.steps)
    return 0 if all_passed else 1


if __name__ == "__main__":
    sys.exit(main())
